// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHvjzcun9MKehYYaa7Vxh5VfeHqaxzaJY',
    appId: '1:682411236951:web:26bc97b447f273fef04d12',
    messagingSenderId: '682411236951',
    projectId: 'noteflow-abd14',
    authDomain: 'noteflow-abd14.firebaseapp.com',
    storageBucket: 'noteflow-abd14.firebasestorage.app',
    measurementId: 'G-Z4TVZ4JR2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChk04x15zSXn-h6MBByaqwHWD9uXsari0',
    appId: '1:682411236951:android:7cb819923506c149f04d12',
    messagingSenderId: '682411236951',
    projectId: 'noteflow-abd14',
    storageBucket: 'noteflow-abd14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyBxktFDWCPQAWRyxjFjKYqg0Rj7Tg8Vg',
    appId: '1:682411236951:ios:9b7d493e6ea7c3fef04d12',
    messagingSenderId: '682411236951',
    projectId: 'noteflow-abd14',
    storageBucket: 'noteflow-abd14.firebasestorage.app',
    iosClientId:
        '682411236951-bfjqr2itdvldms79fl98av19mqrr9pqp.apps.googleusercontent.com',
    iosBundleId: 'com.noteflow.smartNotesAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyBxktFDWCPQAWRyxjFjKYqg0Rj7Tg8Vg',
    appId: '1:682411236951:ios:9b7d493e6ea7c3fef04d12',
    messagingSenderId: '682411236951',
    projectId: 'noteflow-abd14',
    storageBucket: 'noteflow-abd14.firebasestorage.app',
    iosClientId:
        '682411236951-bfjqr2itdvldms79fl98av19mqrr9pqp.apps.googleusercontent.com',
    iosBundleId: 'com.noteflow.smartNotesAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHvjzcun9MKehYYaa7Vxh5VfeHqaxzaJY',
    appId: '1:682411236951:web:e60d6f15ea5c9bdff04d12',
    messagingSenderId: '682411236951',
    projectId: 'noteflow-abd14',
    authDomain: 'noteflow-abd14.firebaseapp.com',
    storageBucket: 'noteflow-abd14.firebasestorage.app',
    measurementId: 'G-CCC39DCK3Z',
  );
}
