import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:flutter_native_splash/flutter_native_splash.dart';

import 'app/app.dart';
import 'features/notes/models/note_model.dart';
import 'features/notes/models/folder_model.dart';
import 'firebase_options.dart';
import 'services/app_config_service.dart';

/// ──────────────────────────────────────────────────────────────
/// NoteFlow — Entry Point
///
/// Initialises Hive (local storage) and Firebase with the
/// platform-specific options generated by FlutterFire CLI,
/// then launches the app.
///
/// Phase 17: Registers FolderAdapter (typeId: 1).
/// ──────────────────────────────────────────────────────────────

// AI NOTE: Main entry point of the Flutter application. Initializes local storage and Firebase.
void main() async {
  WidgetsBinding widgetsBinding = WidgetsFlutterBinding.ensureInitialized();
  FlutterNativeSplash.preserve(widgetsBinding: widgetsBinding);

  bool firebaseReady = false;
  late AppConfigService appConfigService;

  try {
    // Initialise Hive and Firebase concurrently to save time
    await Future.wait([
      Hive.initFlutter(),
      Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      ).then((_) {
        firebaseReady = true;
      }),
    ]);

    // AI FIX: Initialize AppConfigService AFTER Firebase is ready
    appConfigService = AppConfigService();

    // Register the hand-written Hive adapters
    Hive.registerAdapter(NoteAdapter()); // typeId: 0
    Hive.registerAdapter(FolderAdapter()); // typeId: 1

    // Initialize Mobile Ads and fetch initial AppConfig concurrently
    if (firebaseReady) {
      await appConfigService.init();
      await Future.wait([
        MobileAds.instance.initialize(),
        appConfigService.fetchInitialConfig(),
      ]);
    }
  } catch (e) {
    // Fallback if initialization fails
    appConfigService = AppConfigService();
    if (kDebugMode) {
      debugPrint('⚠️ Initialization failed: $e');
      debugPrint('   The app will run in offline mode.');
    }
  }

  runApp(NoteFlowApp(
    firebaseReady: firebaseReady,
    appConfigService: appConfigService,
  ));

  FlutterNativeSplash.remove();
}